// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "item",
    columns: [
      { name: "name", type: "string" },
      { name: "description", type: "string" },
      { name: "category", type: "link", link: { table: "item_category" } },
      { name: "image_url", type: "string", unique: true },
      { name: "price", type: "float" },
    ],
  },
  { name: "item_category", columns: [{ name: "name", type: "string" }] },
];
/** @type { import('../../client/src').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Hermela-Getnet-s-workspace-4okmj6.us-east-1.xata.sh/db/habeshan-clothes",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
